/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microtechmd_blecomm_controller_PumpController */

#ifndef _Included_com_microtechmd_blecomm_controller_PumpController
#define _Included_com_microtechmd_blecomm_controller_PumpController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_microtechmd_blecomm_controller_PumpController
 * Method:    constructor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_microtechmd_blecomm_controller_PumpController_constructor
        (JNIEnv *, jobject);

/*
 * Class:     com_microtechmd_blecomm_controller_PumpController
 * Method:    destructor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_microtechmd_blecomm_controller_PumpController_destructor
        (JNIEnv *, jobject);

/*
 * Class:     com_microtechmd_blecomm_controller_PumpController
 * Method:    getDeviceInfo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_microtechmd_blecomm_controller_PumpController_getDeviceInfo
        (JNIEnv *, jobject);

/*
 * Class:     com_microtechmd_blecomm_controller_PumpController
 * Method:    getHistory
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_microtechmd_blecomm_controller_PumpController_getHistory
        (JNIEnv *, jobject, jint);


JNIEXPORT jint JNICALL Java_com_microtechmd_blecomm_controller_PumpController_setDatetime
        (JNIEnv *, jobject, jstring);

JNIEXPORT jint JNICALL Java_com_microtechmd_blecomm_controller_PumpController_setCgmSn
        (JNIEnv *, jobject, jstring);

JNIEXPORT jint JNICALL Java_com_microtechmd_blecomm_controller_PumpController_setAutoMode
        (JNIEnv *, jobject, jboolean);

JNIEXPORT jint JNICALL Java_com_microtechmd_blecomm_controller_PumpController_getMode
        (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_com_microtechmd_blecomm_controller_PumpController_setMode
        (JNIEnv *, jobject, jint);


JNIEXPORT jint JNICALL Java_com_microtechmd_blecomm_controller_PumpController_setBasalProfile
        (JNIEnv *, jobject, jfloatArray);


JNIEXPORT jint JNICALL Java_com_microtechmd_blecomm_controller_PumpController_setBolusProfile
        (JNIEnv *, jobject, jfloat amountTotal, float bolusRatio, jfloat amountExtended,
         jint intervalExtended);

JNIEXPORT jint JNICALL Java_com_microtechmd_blecomm_controller_PumpController_getBolusProfile
        (JNIEnv *, jobject);


JNIEXPORT jint JNICALL Java_com_microtechmd_blecomm_controller_PumpController_setTemporaryProfile
        (JNIEnv *, jobject, jfloat tempBasal, jint interval);

JNIEXPORT jint JNICALL Java_com_microtechmd_blecomm_controller_PumpController_setSetting
        (JNIEnv *, jobject, jfloatArray value);

JNIEXPORT jint JNICALL Java_com_microtechmd_blecomm_controller_PumpController_setRewinding
        (JNIEnv *, jobject, jfloat amount);

JNIEXPORT jint JNICALL Java_com_microtechmd_blecomm_controller_PumpController_setPriming
        (JNIEnv *, jobject, jfloat amount);

JNIEXPORT jint JNICALL Java_com_microtechmd_blecomm_controller_PumpController_setGlucoseTarget
        (JNIEnv *, jobject, jfloat target, jfloat upper);

JNIEXPORT jint JNICALL Java_com_microtechmd_blecomm_controller_PumpController_setIsf
        (JNIEnv *, jobject, jfloat isf);

//JNIEXPORT jint JNICALL Java_com_microtechmd_blecomm_controller_PumpController_setGlucose
//                (JNIEnv *, jobject, jfloat glucose);

JNIEXPORT jint JNICALL Java_com_microtechmd_blecomm_controller_PumpController_getOcclusion
        (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_com_microtechmd_blecomm_controller_PumpController_setAddress
        (JNIEnv *, jobject);


JNIEXPORT jint JNICALL Java_com_microtechmd_blecomm_controller_PumpController_clearAddress
        (JNIEnv *, jobject);


JNIEXPORT jint JNICALL Java_com_microtechmd_blecomm_controller_PumpController_getSetting
        (JNIEnv *, jobject);

//JNIEXPORT jint JNICALL Java_com_microtechmd_blecomm_controller_PumpController_getPumpCapacityStatus
//        (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_com_microtechmd_blecomm_controller_PumpController_getBasalProfile
        (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_com_microtechmd_blecomm_controller_PumpController_setEventConfirmed
        (JNIEnv *, jobject, jint eventIndex, jint event, jint value);


JNIEXPORT jint JNICALL Java_com_microtechmd_blecomm_controller_PumpController_setBolusRatio
        (JNIEnv *, jobject, jint multiple, jint division);

JNIEXPORT jint JNICALL
Java_com_microtechmd_blecomm_controller_PumpController_setTemporaryPercentProfile
        (JNIEnv *, jobject, jint tempBasalPercent, jint interval);


#ifdef __cplusplus
}
#endif
#endif
