/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microtechmd_blecomm_parser_CgmParser */

#ifndef _Included_com_microtechmd_blecomm_parser_AidexXParser
#define _Included_com_microtechmd_blecomm_parser_AidexXParser
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jobject JNICALL Java_com_microtechmd_blecomm_parser_AidexXParser_getBroadcast
        (JNIEnv *, jclass, jbyteArray);

JNIEXPORT jobject JNICALL Java_com_microtechmd_blecomm_parser_AidexXParser_getFullBroadcast
        (JNIEnv *, jclass, jbyteArray);

JNIEXPORT jobject JNICALL Java_com_microtechmd_blecomm_parser_AidexXParser_getHistories
        (JNIEnv *, jclass, jbyteArray);

JNIEXPORT jobject JNICALL Java_com_microtechmd_blecomm_parser_AidexXParser_getRawHistory
        (JNIEnv *, jclass, jbyteArray);

JNIEXPORT jobject JNICALL Java_com_microtechmd_blecomm_parser_AidexXParser_getAidexXCalibration
        (JNIEnv *, jclass, jbyteArray);

JNIEXPORT jfloatArray JNICALL Java_com_microtechmd_blecomm_parser_AidexXParser_getParam
        (JNIEnv *, jclass, jbyteArray);

JNIEXPORT jobject JNICALL Java_com_microtechmd_blecomm_parser_AidexXParser_getAidexXInstantHistory
        (JNIEnv *, jclass, jbyteArray);

JNIEXPORT jobject JNICALL Java_com_microtechmd_blecomm_parser_AidexXParser_getScanResponseInfo
        (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
