/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microtechmd_blecomm_controller_PumpController */

#ifndef _Included_com_microtechmd_blecomm_controller_BgmController
#define _Included_com_microtechmd_blecomm_controller_BgmController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_microtechmd_blecomm_controller_BgmController
 * Method:    constructor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_microtechmd_blecomm_controller_BgmController_constructor
  (JNIEnv *, jobject);

/*
 * Class:     com_microtechmd_blecomm_controller_BgmController
 * Method:    destructor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_microtechmd_blecomm_controller_BgmController_destructor
  (JNIEnv *, jobject);

/*
 * Class:     com_microtechmd_blecomm_controller_BgmController
 * Method:    getDeviceInfo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_microtechmd_blecomm_controller_BgmController_getDeviceInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_microtechmd_blecomm_controller_BgmController
 * Method:    getHistory
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_microtechmd_blecomm_controller_BgmController_getHistory
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
