/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microtechmd_blecomm_controller_BleControllerInfo */

#ifndef _Included_com_microtechmd_blecomm_controller_BleControllerInfo
#define _Included_com_microtechmd_blecomm_controller_BleControllerInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
