/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microtechmd_blecomm_controller_BleController_DiscoveredCallback */

#ifndef _Included_com_microtechmd_blecomm_controller_BleController_DiscoveredCallback
#define _Included_com_microtechmd_blecomm_controller_BleController_DiscoveredCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
