/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "../pumpcomm.h"
/* Header for class com_microtechmd_blecomm_parser_PumpParser */

#ifndef _Included_com_microtechmd_blecomm_parser_PumpParser
#define _Included_com_microtechmd_blecomm_parser_PumpParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_microtechmd_blecomm_parser_PumpParser
 * Method:    setDeviceInfoClass
 * Signature: (Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_com_microtechmd_blecomm_parser_PumpParser_setDeviceInfoClass
        (JNIEnv *, jclass, jclass);

/*
 * Class:     com_microtechmd_blecomm_parser_PumpParser
 * Method:    setHistoryClass
 * Signature: (Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_com_microtechmd_blecomm_parser_PumpParser_setHistoryClass
        (JNIEnv *, jclass, jclass);

/*
 * Class:     com_microtechmd_blecomm_parser_PumpParser
 * Method:    getDeviceInfo
 * Signature: ()Lcom/microtechmd/blecomm/parser/PumpDeviceEntity;
 */
JNIEXPORT jobject JNICALL Java_com_microtechmd_blecomm_parser_PumpParser_getDeviceInfo
        (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_microtechmd_blecomm_parser_PumpParser
 * Method:    getHistory
 * Signature: ([B)Lcom/microtechmd/blecomm/parser/PumpHistoryEntity;
 */
JNIEXPORT jobject JNICALL Java_com_microtechmd_blecomm_parser_PumpParser_getHistory
        (JNIEnv *, jclass, jbyteArray);


JNIEXPORT void JNICALL
Java_com_microtechmd_blecomm_parser_PumpParser_setBroadcastClass(JNIEnv *env, jclass clazz,
                                                                 jclass broadcast_class);


JNIEXPORT jobject JNICALL
Java_com_microtechmd_blecomm_parser_PumpParser_getBroadcast(JNIEnv *env, jclass clazz,
                                                            jbyteArray bytes);

JNIEXPORT jfloatArray JNICALL
Java_com_microtechmd_blecomm_parser_PumpParser_getBolus(JNIEnv *env, jclass clazz,
                                                            jbyteArray bytes);

#ifdef __cplusplus
}
#endif
#endif
