/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microtechmd_blecomm_parser_PumpParser */

#ifndef _Included_com_microtechmd_blecomm_parser_BgmParser
#define _Included_com_microtechmd_blecomm_parser_BgmParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_microtechmd_blecomm_parser_PumpParser
 * Method:    setDeviceInfoClass
 * Signature: (Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_com_microtechmd_blecomm_parser_BgmParser_setDeviceInfoClass
  (JNIEnv *, jclass, jclass);

/*
 * Class:     com_microtechmd_blecomm_parser_CgmParser
 * Method:    setHistoryClass
 * Signature: (Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_com_microtechmd_blecomm_parser_BgmParser_setHistoryClass
  (JNIEnv *, jclass, jclass);

/*
 * Class:     com_microtechmd_blecomm_parser_CgmParser
 * Method:    getDeviceInfo
 * Signature: ()Lcom/microtechmd/blecomm/parser/PumpDeviceEntity;
 */
JNIEXPORT jobject JNICALL Java_com_microtechmd_blecomm_parser_BgmParser_getDeviceInfo
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_microtechmd_blecomm_parser_CgmParser
 * Method:    getHistory
 * Signature: ([B)Lcom/microtechmd/blecomm/parser/PumpHistoryEntity;
 */
JNIEXPORT jobject JNICALL Java_com_microtechmd_blecomm_parser_BgmParser_getHistory
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
