{
  "formatVersion": "1.1",
  "component": {
    "group": "com.microtech.plugins",
    "module": "aidexPlugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aidexPlugin-1.0.0.jar",
          "url": "aidexPlugin-1.0.0.jar",
          "size": 40112,
          "sha512": "61c51615b186e0ac9e90dab515e1b5c44c6c20f1ac1110c374da639dd3b0f542411a101868455a0a3db3151333d17dbac33c56804b1654c3aa873b7995e26f10",
          "sha256": "10653e0a6eec93c3bbe35d1db91b6463f9eca6c28e2fd5f618017f384c09a5f5",
          "sha1": "b6d9a57ea455cc13c1df8e5e34edd3dc0b7b34d5",
          "md5": "8f118965a16211362de2cf65ae85106d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "aidexPlugin-1.0.0.jar",
          "url": "aidexPlugin-1.0.0.jar",
          "size": 40112,
          "sha512": "61c51615b186e0ac9e90dab515e1b5c44c6c20f1ac1110c374da639dd3b0f542411a101868455a0a3db3151333d17dbac33c56804b1654c3aa873b7995e26f10",
          "sha256": "10653e0a6eec93c3bbe35d1db91b6463f9eca6c28e2fd5f618017f384c09a5f5",
          "sha1": "b6d9a57ea455cc13c1df8e5e34edd3dc0b7b34d5",
          "md5": "8f118965a16211362de2cf65ae85106d"
        }
      ]
    }
  ]
}
