{
  "formatVersion": "1.1",
  "component": {
    "group": "com.microtech.plugins",
    "module": "aidexPlugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aidexPlugin-1.0.0.jar",
          "url": "aidexPlugin-1.0.0.jar",
          "size": 40112,
          "sha512": "3cb9c1e3b94349d579979b980a959aca83c604648831dc8478da5c267ac0ed9430923aa2012578d34c19640d82c6f3339a2a7d8db3e8e83a290eec7633d23e2d",
          "sha256": "962e6110e09ca10355e2e22330524c0ff7f570ff3b9c05e8389a96d5afba3b37",
          "sha1": "9b86be89f70a8907655880a5477186478f20b7d2",
          "md5": "fd3ec7589abfff501def2a06d25dc02f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "aidexPlugin-1.0.0.jar",
          "url": "aidexPlugin-1.0.0.jar",
          "size": 40112,
          "sha512": "3cb9c1e3b94349d579979b980a959aca83c604648831dc8478da5c267ac0ed9430923aa2012578d34c19640d82c6f3339a2a7d8db3e8e83a290eec7633d23e2d",
          "sha256": "962e6110e09ca10355e2e22330524c0ff7f570ff3b9c05e8389a96d5afba3b37",
          "sha1": "9b86be89f70a8907655880a5477186478f20b7d2",
          "md5": "fd3ec7589abfff501def2a06d25dc02f"
        }
      ]
    }
  ]
}
